apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
data:
  SPRING_DATASOURCE_URL: amRiYzpteXNxbDovL2NsaXBzaG90LXByb2Nlc3Nvci1teXNxbDozMzA2L2NsaXBzaG90LXByb2Nlc3Nvcj9jcmVhdGVEYXRhYmFzZUlmTm90RXhpc3Q9dHJ1ZSZ6ZXJvRGF0ZVRpbWVCZWhhdmlvcj1jb252ZXJ0VG9OdWxsJnVzZVNTTD1mYWxzZSZhbGxvd1B1YmxpY0tleVJldHJpZXZhbD10cnVl
  SPRING_DATASOURCE_USERNAME: YWRtaW4xMjM=
  SPRING_DATASOURCE_PASSWORD: YWRtaW4xMjM=
