CREATE TABLE IF NOT EXISTS video_task (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NULL,
    video_id VARCHAR(255) NOT NULL,
    video_url VARCHAR(255) NOT NULL,
    status ENUM('PROCESSING', 'COMPLETED', 'FAILED', 'EXPIRED') DEFAULT 'PROCESSING',
    user_id BIGINT NOT NULL,
    frames_url VARCHAR(255) DEFAULT NULL,
    retry_count INT DEFAULT 0,
    error_message VARCHAR(255) DEFAULT NULL
);