apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:management
        ports:
        - containerPort: 15672
        - containerPort: 5672
        volumeMounts:
        - name: rabbitmq-definitions-volume
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
        env:
        - name: RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS
          value: "-rabbitmq_management load_definitions '/etc/rabbitmq/definitions.json'"
      volumes:
      - name: rabbitmq-definitions-volume
        configMap:
          name: rabbitmq-definitions
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 31000
    name: http
  - port: 5672
    targetPort: 5672
    nodePort: 31001
    name: amqp
  selector:
    app: rabbitmq
